name: Deploy GitHub Pages

on:
  push:
    branches:
      - mainhttps://github.com/Triumvira84/ia-2paname/actions

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Pages
        uses: actions/configure-pages@v1

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: .
